service: custom-resources
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  profile: default # name of AWS profile (defined in ~/.aws/credentials)
  memorySize: 128 # Default is 1024
  timeout: 2 # The default is 6 seconds, max 30
  logRetentionInDays: 1 # keep logs for 1 day
  deploymentBucket:
    name: ng-deployments # change it
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow # for creating ssm parameters
      Action:
        - ssm:PutParameter
        - ssm:DeleteParameter
      Resource: '*'
    - Effect: Allow # for getting api keys
      Action:
        - apigateway:GET
      Resource: '*'
package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  CustomResource:
    handler: bin/custom-resource

resources:
  Outputs:
    ServiceToken:
      Description: "Arn of CustomResource lambda"
      Value: !GetAtt CustomResourceLambdaFunction.Arn
      Export: 
        Name: ${self:service}:${self:provider.stage}:ServiceToken
